
modLoader="javafml"

loaderVersion="[40,)"

license="LGPLv3"

[[mods]]

modId="experienced_crops"

version = "${version}"

displayName="Experienced Crops"

logoFile="icon.png"

authors="Ordana"

description='''
Obtain xp orbs from fully grown crops!
'''

[[dependencies.experienced_crops]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.experienced_crops]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"